---
title: "key"
author: "Sofia Illescas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

# 0. Installing R and RStudio

https://posit.co/download/rstudio-desktop/

# 1. Installing packages

```{r install_packages, warning=FALSE, message=FALSE}
if(!require(here)) install.packages("here")
if(!require(qwraps2)) install.packages("qwraps2")
if(!require(here)) install.packages("readxl")
if(!require(qwraps2)) install.packages("writexl")
if(!require(tidyverse)) install.packages("tidyverse")
```

# 2. Importing libraries

```{r library_imports, message=FALSE, warning=FALSE}
library(here)
library(qwraps2)
library(readxl)
library(writexl)
library(tidyverse)
```

# 3. Importing data

https://github.com/sofiaillescasb/teaching-R/blob/main/R%20course/dataset/titanic_dataset.xlsx

```{r data_imports}
dbset <- read_excel(here("dataset/titanic_dataset.xlsx"))
#Inspecting data
head(dbset)
head(dbset[,"Name"])
head(dbset[["Name"]])
head(dbset$Name)

#Subsetting
dbset[dbset$Sex=="female"&dbset$Pclass==1,]
subset(dbset, Sex=="female"&Pclass==1)
dbset %>% filter(Sex=="female"&Pclass==1) 

#Change variable types if they don't make sense

# "Age" should be a number, not characters
dbset$Age <- as.numeric(dbset$Age)

# "Survived" should be a factor meaning yes/no, instead of a numeric value
dbset$Survived <- factor(dbset$Survived)

# "Pclass" should also be a factor instead of a number
dbset$Pclass <- factor(dbset$Pclass)

```

# 4. Summarizing and visualizing data

```{r finding_interesting_groups}
cat("Survival by sex:", sep = "\n")
cat("", sep = "\n")
xtabs(~Sex+Survived,data = dbset)
cat("", sep = "\n")

cat("Survival by class:", sep = "\n")
cat("", sep = "\n")
xtabs(~Pclass+Survived,data = dbset)
cat("", sep = "\n")

cat("Male survival by class:", sep = "\n")
cat("", sep = "\n")
xtabs(~Pclass+Survived,data = dbset,subset = Sex=="male")
cat("", sep = "\n")

cat("Female survival by class:", sep = "\n")
cat("", sep = "\n")
xtabs(~Pclass+Survived,data = dbset,subset = Sex=="female")
cat("", sep = "\n")
```

```{r missing-values}
# We can't use missing values, so we eliminate all columns with more than 80% NAs

data <- dbset[,colSums(is.na(dbset)) < length(rownames(dbset))*0.2]

colnames(data[,colSums(is.na(data)) > 0])

# In this case we'll ignore missing values, but we could use more sophisticated methods to impute them
data <- na.omit(data)
```



```{r visualization}

all_survivors <- subset(data, Survived==1)
all_casualties <- subset(data, Survived==0)

data %>%
  ggplot(aes(x=x,fill=Sex)) +
  geom_histogram(aes(x=Age,y = after_stat(count)),col="black", data=subset(data, Sex=="female")) +
  geom_histogram(aes(x=Age,y = -after_stat(count)),col="black", data=subset(data, Sex=="male")) +
  coord_flip() +
  theme_minimal() +
  scale_y_continuous(
    labels = abs
    ) +
  labs(x = "Age", y = "Count", fill = "Age", title = "Age distribution by sex")
  


female_casualties <- subset(data, Sex=="female"&Survived==0)
male_survivors <- subset(data, Sex=="male"&Survived==1)


female_casualties %>%
  ggplot(aes(x=Age,fill=Pclass)) +
  geom_density(alpha=0.3) +
  labs(title = "Female casualties distribution", x = "Age", y = "Count", fill = "Passenger class")


male_survivors %>%
  ggplot(aes(x=Age,fill=Pclass)) +
  geom_density(alpha=0.3) +
  labs(title = "Male survivors distribution", x = "Age", y = "Count", fill = "Passenger class")


```


```{r summary_statistics}

# For continuous variables raw
variable_names <- "Age"

# Create a list to store summary statistics
summary_list <- list()

# Iterate over the variable names to compute statistics
for (variable in variable_names) {
  summary_list[[variable]] <- list(
    "min" = as.formula(paste0("~ min(`", variable, "`)")),
    "median (iqr)" = as.formula(paste0("~ median_iqr(`", variable, "`)")),
    "max" = as.formula(paste0("~ max(`", variable, "`)")),
    "mean (CI)" = as.formula(paste0("~ qwraps2::frmtci(mean_ci(`", variable, "`, show_level = TRUE))")),
    "SD" = as.formula(paste0("~ sd(`", variable, "`)"))
  )
}

# Create a summary table
summary_table_data <- summary_table(dplyr::group_by(data, Sex, Survived), summary_list)# Let's group passengers by survival, 0=died, 1=survived
rownames_summary <- rownames(summary_table_data)
summary_table_data <- data.frame(cbind(rep(variable_names, each = 5), summary_table_data), check.names = FALSE) #change for the number of statistics to calculate
colnames(summary_table_data)[1] <- "Variable" #Change to name that makes sense
summary_table_data <- rownames_to_column(summary_table_data, var = "Statistic")
summary_table_data$Statistic <- rownames_summary

# Pivot the data for a wider format
summary_statistics_grouped <- pivot_wider(summary_table_data, names_from = Variable, values_from = colnames(summary_table_data)[-c(1, 2)]) 
View(summary_statistics_grouped)
```

# 5. 
