---
title: "Titanic Analysis"
author: "Sofia Illescas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 1. Importing libraries

```{r libraries, include=FALSE}
library(here)
library(readxl)
library(patchwork)
library(tidyverse)
```

# 2. Importing data

```{r data_imports}

dbset <- read_excel(here("dataset/titanic_dataset.xlsx"))

# Y si tuvieramos más de un hoja de Excel?
# path <- here("dataset/titanic_dataset.xlsx")
# dbset_list <- lapply(excel_sheets(path), read_excel, path = path)

# Vamos a revisar los datos
# Las columnas deben ser las variables dependientes y las filas deben ser observaciones
head(dbset)


colnames(dbset)
rownames(dbset)
```

# 3. Cleaning data

```{r data_types_missing_values}

dbset <- dbset %>%
  mutate_at(c("PassengerId", "Survived", "Pclass", "Sex", "Embarked","Ticket"), factor) %>%
  mutate_at(c("Age","Fare"), as.numeric)

# keep_cols <- c()
# 
# for (i in colnames(dbset)) {
#   if(sum(is.na(dbset[[i]])) <= 0.2*nrow(dbset)) {
#     keep_cols <- c(keep_cols,i)
#   } 
#   else next
# }
# 
# 
# keep_cols <- colnames(dbset)[sapply(colnames(dbset), function(x) sum(is.na(dbset[[x]])) <= 0.2*nrow(dbset))]
# 
# sum(is.na(dbset[["Cabin"]]))
# 0.2*nrow(dbset)



dbset_filtered <- dbset %>%
  select_if(~ sum(is.na(.)) <= 0.2*nrow(dbset))

dbset
dbset_no_missing <- dbset_filtered[complete.cases(dbset_filtered),]
```

```{r}

p1 <- dbset_no_missing %>%
  ggplot(aes(x=Age, fill=Sex, color=Sex)) +
  geom_density(aes(y=after_stat(count)),alpha=0.6) +
  facet_wrap(~ Pclass, scales = "free")

age_ranges <- pretty(dbset_no_missing$Age, n=20)


dbset_age_split <- dbset_no_missing %>%
  mutate(Age.Range = cut(Age, age_ranges, include.lowest = FALSE))


p2 <- dbset_age_split %>%
  group_by(Sex, Age.Range) %>% 
  reframe(Passengers = n()) %>%
  mutate(Passengers=if_else(Sex=="female",-Passengers,Passengers)) %>%
  ggplot(aes(x = Age.Range,
         y = Passengers,
         fill = Sex)) + 
  coord_flip() +
geom_bar(stat = "identity") +
   scale_y_continuous(
     breaks = seq(-100,100,10),
     limits = c(-100,100),
     labels = abs(seq(-100,100,10))) 

p1 + p2

p1 / p2 & plot_annotation(tag_level = "A")

p1 / p2 & plot_annotation(tag_level = "a")

p1 / p2 & plot_annotation(tag_level = "I")

p1 / p2 & plot_annotation(tag_level = "A") & plot_layout(heights = c(1,2))


# library(apyramid)
# 
# dbset_age_split$Age.Range <- as.factor(dbset_age_split$Age.Range)
# 
# age_pyramid(dbset_age_split, age_group = "Age.Range", split_by = "Sex", proportional = FALSE, stack_by = "Pclass")
```

```{r}
dbset_no_missing %>%
  ggplot(aes(x=Age, fill=Pclass, color=Pclass)) +
  geom_density(aes(y=after_stat(count)),alpha=0.6) 

table(dbset_no_missing$Pclass)/nrow(dbset_no_missing)*100

dbset_no_missing %>%
  ggplot(aes(Survived, fill=Pclass, color=Pclass)) +
  geom_bar(alpha=0.6, position = "fill") 

dbset_no_missing %>%
  ggplot(aes(Pclass, fill=Survived, color=Survived)) +
  geom_bar(alpha=0.6, position = "fill") 

dbset_no_missing %>%
  ggplot(aes(Sex, fill=Survived, color=Survived)) +
  geom_bar(alpha=0.6, position = "fill") 

dbset_no_missing_p_ticket <- dbset_no_missing %>%
  group_by(Ticket) %>%
  mutate(Per_ticket=n()) %>%
  mutate(Fare=Fare/Per_ticket) %>%
  ungroup()

```

```{r anova}

fare_anova <- aov(Fare ~ Pclass, dbset_no_missing_p_ticket)
coefs_fare <- coefficients(fare_anova)
tukey_fare <- TukeyHSD(fare_anova)
TukeyHSD(fare_anova)

```
